# Generated by Django 6.0.4 on 2026-05-05 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_rename_category_categories_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={},
        ),
    ]
